name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    continue-on-error: false

    env:
      CLOUDFLARE_ENDPOINT: 'CLOUDFLARE_ENDPOINT'
      CLOUDFLARE_ACCESS_KEY_ID: 'CLOUDFLARE_ACCESS_KEY_ID'
      CLOUDFLARE_SECRET_ACCESS_KEY: 'CLOUDFLARE_SECRET_ACCESS_KEY'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "CLOUDFLARE_ENDPOINT=$CLOUDFLARE_ENDPOINT" >> $GITHUB_ENV
        echo "CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY" >> $GITHUB_ENV

    - name: Install PNPM
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run unit tests
      run: pnpm run test:unit
      if: failure()
    - uses: andymckay/cancel-action@0.4

    - name: Run end-to-end tests
      run: pnpm run test:e2e
      if: failure()
    - uses: andymckay/cancel-action@0.4

  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build -t saldsdev/share-it-api:${{ steps.generate_sha.outputs.sha }} .

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push saldsdev/share-it-api:${{ steps.generate_sha.outputs.sha }}
        docker tag saldsdev/share-it-api:${{ steps.generate_sha.outputs.sha }} saldsdev/share-it-api:latest
        docker push saldsdev/share-it-api:latest

