name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PNPM
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run unit tests
      run: pnpm run test:unit

    - name: Run end-to-end tests
      run: pnpm run test:e2e

  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build -t saldsdev/share-it-api:${{ steps.generate_sha.outputs.sha }} .

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push saldsdev/share-it-api:${{ steps.generate_sha.outputs.sha }}
        docker tag saldsdev/share-it-api:${{ steps.generate_sha.outputs.sha }} saldsdev/share-it-api:latest
        docker push saldsdev/share-it-api:latest

